// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard";

export const IndexRecord = autoguard.guards.Object.of({
	"token": autoguard.guards.Union.of(
		autoguard.guards.Union.of(
			autoguard.guards.Boolean,
			autoguard.guards.Null,
			autoguard.guards.Number,
			autoguard.guards.String,
			autoguard.guards.Undefined
		),
		autoguard.guards.Undefined
	),
	"index": autoguard.guards.Number
});

export type IndexRecord = ReturnType<typeof IndexRecord["as"]>;

export namespace Autoguard {
	export const Guards = {
		"IndexRecord": autoguard.guards.Reference.of(() => IndexRecord)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
