// This file was auto-generated by @joelek/autoguard. Edit at own risk.

import * as autoguard from "@joelek/autoguard/dist/lib-shared";

export const IndexRecord: autoguard.serialization.MessageGuard<IndexRecord> = autoguard.guards.Object.of({
	"index": autoguard.guards.Number
}, {
	"token": autoguard.guards.Union.of(
		autoguard.guards.Boolean,
		autoguard.guards.Null,
		autoguard.guards.Number,
		autoguard.guards.String,
		autoguard.guards.Undefined
	)
});

export type IndexRecord = autoguard.guards.Object<{
	"index": autoguard.guards.Number
}, {
	"token": autoguard.guards.Union<[
		autoguard.guards.Boolean,
		autoguard.guards.Null,
		autoguard.guards.Number,
		autoguard.guards.String,
		autoguard.guards.Undefined
	]>
}>;

export namespace Autoguard {
	export const Guards = {
		"IndexRecord": autoguard.guards.Reference.of(() => IndexRecord)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
