// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type Person = {
	"person_id": string,
	"name": string
};

export const Person = autoguard.Object.of<Person>({
	"person_id": autoguard.String,
	"name": autoguard.String
});

export type Autoguard = {
	"Person": Person
};

export const Autoguard = {
	"Person": Person
};
