// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";
import { Context, Device } from "./objects";

export type SetContext = {
	"context"?: Context
};

export const SetContext = autoguard.Object.of<SetContext>({
	"context": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Reference.of<Context>(() => Context)
	)
});

export type SetDevice = {
	"device"?: Device
};

export const SetDevice = autoguard.Object.of<SetDevice>({
	"device": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Reference.of<Device>(() => Device)
	)
});

export type SetDevices = {
	"devices": Device[]
};

export const SetDevices = autoguard.Object.of<SetDevices>({
	"devices": autoguard.Array.of(autoguard.Reference.of<Device>(() => Device))
});

export type SetIndex = {
	"index"?: number
};

export const SetIndex = autoguard.Object.of<SetIndex>({
	"index": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Number
	)
});

export type SetLocalDevice = {
	"device": Device
};

export const SetLocalDevice = autoguard.Object.of<SetLocalDevice>({
	"device": autoguard.Reference.of<Device>(() => Device)
});

export type SetPlayback = {
	"playback": boolean
};

export const SetPlayback = autoguard.Object.of<SetPlayback>({
	"playback": autoguard.Boolean
});

export type SetProgress = {
	"progress"?: number
};

export const SetProgress = autoguard.Object.of<SetProgress>({
	"progress": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Number
	)
});

export type SetToken = {
	"token"?: string
};

export const SetToken = autoguard.Object.of<SetToken>({
	"token": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.String
	)
});

export type Autoguard = {
	"SetContext": SetContext,
	"SetDevice": SetDevice,
	"SetDevices": SetDevices,
	"SetIndex": SetIndex,
	"SetLocalDevice": SetLocalDevice,
	"SetPlayback": SetPlayback,
	"SetProgress": SetProgress,
	"SetToken": SetToken
};

export const Autoguard = {
	"SetContext": SetContext,
	"SetDevice": SetDevice,
	"SetDevices": SetDevices,
	"SetIndex": SetIndex,
	"SetLocalDevice": SetLocalDevice,
	"SetPlayback": SetPlayback,
	"SetProgress": SetProgress,
	"SetToken": SetToken
};
