// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type Context = ContextItem[];

export const Context = autoguard.Array.of(autoguard.Reference.of<ContextItem>(() => ContextItem));

export type ContextItem = {
	"file_id": string,
	"title": string,
	"subtitle": string
};

export const ContextItem = autoguard.Object.of<ContextItem>({
	"file_id": autoguard.String,
	"title": autoguard.String,
	"subtitle": autoguard.String
});

export type Device = {
	"id": string,
	"type": string,
	"name": string
};

export const Device = autoguard.Object.of<Device>({
	"id": autoguard.String,
	"type": autoguard.String,
	"name": autoguard.String
});

export type Session = {
	"context"?: Context,
	"device"?: Device,
	"index"?: number,
	"playback": boolean,
	"progress"?: number
};

export const Session = autoguard.Object.of<Session>({
	"context": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Reference.of<Context>(() => Context)
	),
	"device": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Reference.of<Device>(() => Device)
	),
	"index": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Number
	),
	"playback": autoguard.Boolean,
	"progress": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.Number
	)
});

export type Autoguard = {
	"Context": Context,
	"ContextItem": ContextItem,
	"Device": Device,
	"Session": Session
};

export const Autoguard = {
	"Context": Context,
	"ContextItem": ContextItem,
	"Device": Device,
	"Session": Session
};
