// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard/dist/lib-shared";
import { Actor } from ".././objects";
import { Album } from ".././objects";
import { AlbumContext } from ".././objects";
import { Artist } from ".././objects";
import { ArtistContext } from ".././objects";
import { Disc } from ".././objects";
import { DiscContext } from ".././objects";
import { Entity } from ".././objects";
import { Episode } from ".././objects";
import { EpisodeContext } from ".././objects";
import { ErrorMessage } from ".././messages";
import { Genre } from ".././objects";
import { Movie } from ".././objects";
import { MovieContext } from ".././objects";
import { Playlist } from ".././objects";
import { PlaylistContext } from ".././objects";
import { PlaylistItem } from ".././objects";
import { RegisterRequest } from ".././messages";
import { RegisterResponse } from ".././messages";
import { Season } from ".././objects";
import { SeasonContext } from ".././objects";
import { Show } from ".././objects";
import { ShowContext } from ".././objects";
import { Track } from ".././objects";
import { TrackContext } from ".././objects";
import { User } from ".././objects";
import { Year } from ".././objects";

export const ActorResult: autoguard.serialization.MessageGuard<ActorResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Actor),
	"rank": autoguard.guards.Number
}, {});

export type ActorResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Actor>,
	"rank": autoguard.guards.Number
}, {}>;

export const AlbumResult: autoguard.serialization.MessageGuard<AlbumResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Album),
	"rank": autoguard.guards.Number
}, {});

export type AlbumResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Album>,
	"rank": autoguard.guards.Number
}, {}>;

export const ArtistResult: autoguard.serialization.MessageGuard<ArtistResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Artist),
	"rank": autoguard.guards.Number
}, {});

export type ArtistResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Artist>,
	"rank": autoguard.guards.Number
}, {}>;

export const DiscResult: autoguard.serialization.MessageGuard<DiscResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Disc),
	"rank": autoguard.guards.Number
}, {});

export type DiscResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Disc>,
	"rank": autoguard.guards.Number
}, {}>;

export const EpisodeResult: autoguard.serialization.MessageGuard<EpisodeResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Episode),
	"rank": autoguard.guards.Number
}, {});

export type EpisodeResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Episode>,
	"rank": autoguard.guards.Number
}, {}>;

export const GenreResult: autoguard.serialization.MessageGuard<GenreResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Genre),
	"rank": autoguard.guards.Number
}, {});

export type GenreResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Genre>,
	"rank": autoguard.guards.Number
}, {}>;

export const MovieResult: autoguard.serialization.MessageGuard<MovieResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Movie),
	"rank": autoguard.guards.Number
}, {});

export type MovieResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Movie>,
	"rank": autoguard.guards.Number
}, {}>;

export const PlaylistResult: autoguard.serialization.MessageGuard<PlaylistResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Playlist),
	"rank": autoguard.guards.Number
}, {});

export type PlaylistResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Playlist>,
	"rank": autoguard.guards.Number
}, {}>;

export const SeasonResult: autoguard.serialization.MessageGuard<SeasonResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Season),
	"rank": autoguard.guards.Number
}, {});

export type SeasonResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Season>,
	"rank": autoguard.guards.Number
}, {}>;

export const ShowResult: autoguard.serialization.MessageGuard<ShowResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Show),
	"rank": autoguard.guards.Number
}, {});

export type ShowResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Show>,
	"rank": autoguard.guards.Number
}, {}>;

export const TrackResult: autoguard.serialization.MessageGuard<TrackResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Track),
	"rank": autoguard.guards.Number
}, {});

export type TrackResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Track>,
	"rank": autoguard.guards.Number
}, {}>;

export const UserResult: autoguard.serialization.MessageGuard<UserResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => User),
	"rank": autoguard.guards.Number
}, {});

export type UserResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<User>,
	"rank": autoguard.guards.Number
}, {}>;

export const YearResult: autoguard.serialization.MessageGuard<YearResult> = autoguard.guards.Object.of({
	"entity": autoguard.guards.Reference.of(() => Year),
	"rank": autoguard.guards.Number
}, {});

export type YearResult = autoguard.guards.Object<{
	"entity": autoguard.guards.Reference<Year>,
	"rank": autoguard.guards.Number
}, {}>;

export namespace Autoguard {
	export const Guards = {
		"ActorResult": autoguard.guards.Reference.of(() => ActorResult),
		"AlbumResult": autoguard.guards.Reference.of(() => AlbumResult),
		"ArtistResult": autoguard.guards.Reference.of(() => ArtistResult),
		"DiscResult": autoguard.guards.Reference.of(() => DiscResult),
		"EpisodeResult": autoguard.guards.Reference.of(() => EpisodeResult),
		"GenreResult": autoguard.guards.Reference.of(() => GenreResult),
		"MovieResult": autoguard.guards.Reference.of(() => MovieResult),
		"PlaylistResult": autoguard.guards.Reference.of(() => PlaylistResult),
		"SeasonResult": autoguard.guards.Reference.of(() => SeasonResult),
		"ShowResult": autoguard.guards.Reference.of(() => ShowResult),
		"TrackResult": autoguard.guards.Reference.of(() => TrackResult),
		"UserResult": autoguard.guards.Reference.of(() => UserResult),
		"YearResult": autoguard.guards.Reference.of(() => YearResult)
	};

	export type Guards = { [A in keyof typeof Guards]: ReturnType<typeof Guards[A]["as"]>; };

	export const Requests = {
		"POST:/auth/": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"x-circus-username": autoguard.guards.String,
					"x-circus-password": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"payload": autoguard.api.Binary
		}),
		"POST:/users/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Reference.of(() => RegisterRequest)
		}, {
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Options
			),
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number,
					"cues": autoguard.guards.Boolean
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/actors/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/actors/<actor_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"actor_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/actors/<actor_id>/movies/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"actor_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/actors/<actor_id>/shows/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"actor_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/albums/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getNewAlbums": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/albums/<album_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"album_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getAlbumDiscs": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"album_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getAlbumContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"album_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/artists/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/artists/<artist_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"artist_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getArtistAlbums": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"artist_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getArtistContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"artist_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/discs/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/discs/<disc_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"disc_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getDiscTracks": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"disc_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getDiscContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"disc_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/episodes/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/episodes/<episode_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"episode_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getEpisodeContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"episode_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/genres/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/genres/<genre_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"genre_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/genres/<genre_id>/movies/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"genre_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/genres/<genre_id>/shows/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"genre_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/movies/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getNewMovies": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/movies/<movie_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"movie_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/movies/<movie_id>/suggestions/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"movie_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getMovieContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"movie_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getMovieActors": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"movie_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/playlists/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/playlists/<playlist_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"playlist_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getPlaylistItems": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"playlist_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getPlaylistContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"playlist_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/seasons/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/seasons/<season_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"season_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getSeasonEpisodes": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"season_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getSeasonContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"season_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/shows/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/shows/<show_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"show_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getShowSeasons": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"show_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getShowContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"show_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getShowActors": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"show_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/tracks/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/tracks/<track_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"track_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/tracks/<track_id>/playlists/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"track_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getTrackContext": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"track_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/users/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/users/<user_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"user_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/users/<user_id>/albums/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"user_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"getUserArtists": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"user_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/users/<user_id>/playlists/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"user_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/users/<user_id>/shows/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"user_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/years/<query>": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"query": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/years/<year_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"year_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/years/<year_id>/albums/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"year_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/years/<year_id>/movies/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"year_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {
					"anchor": autoguard.guards.String,
					"offset": autoguard.guards.Number,
					"limit": autoguard.guards.Number
				}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/files/<file_id>/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"file_id": autoguard.guards.String,
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/statistics/": autoguard.guards.Object.of({
			"options": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"token": autoguard.guards.String
				}, {}),
				autoguard.api.Options
			)
		}, {
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		})
	};

	export type Requests = { [A in keyof typeof Requests]: ReturnType<typeof Requests[A]["as"]>; };

	export const Responses = {
		"POST:/auth/": autoguard.guards.Object.of({
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({
					"x-circus-token": autoguard.guards.String
				}, {}),
				autoguard.api.Headers
			)
		}, {
			"status": autoguard.guards.Number,
			"payload": autoguard.api.Binary
		}),
		"POST:/users/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Union.of(
				autoguard.guards.Reference.of(() => RegisterResponse),
				autoguard.guards.Reference.of(() => ErrorMessage)
			)
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"entities": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Entity))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/actors/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => ActorResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/actors/<actor_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"actor": autoguard.guards.Reference.of(() => Actor)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/actors/<actor_id>/movies/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"movies": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Movie))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/actors/<actor_id>/shows/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"shows": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Show))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/albums/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => AlbumResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getNewAlbums": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"albums": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Album))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/albums/<album_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"album": autoguard.guards.Reference.of(() => Album)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getAlbumDiscs": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"discs": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Disc))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getAlbumContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => AlbumContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/artists/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => ArtistResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/artists/<artist_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"artist": autoguard.guards.Reference.of(() => Artist),
				"tracks": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Track)),
				"appearances": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Album))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getArtistAlbums": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"albums": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Album))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getArtistContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => ArtistContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/discs/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => DiscResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/discs/<disc_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"disc": autoguard.guards.Reference.of(() => Disc)
			}, {
				"last": autoguard.guards.Reference.of(() => Disc),
				"next": autoguard.guards.Reference.of(() => Disc)
			})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getDiscTracks": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"tracks": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Track))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getDiscContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => DiscContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/episodes/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => EpisodeResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/episodes/<episode_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"episode": autoguard.guards.Reference.of(() => Episode)
			}, {
				"last": autoguard.guards.Reference.of(() => Episode),
				"next": autoguard.guards.Reference.of(() => Episode)
			})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getEpisodeContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => EpisodeContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/genres/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => GenreResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/genres/<genre_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"genre": autoguard.guards.Reference.of(() => Genre)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/genres/<genre_id>/movies/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"movies": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Movie))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/genres/<genre_id>/shows/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"shows": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Show))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/movies/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => MovieResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getNewMovies": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"movies": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Movie))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/movies/<movie_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"movie": autoguard.guards.Reference.of(() => Movie),
				"actors": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Actor))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/movies/<movie_id>/suggestions/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"movies": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Movie))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getMovieContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => MovieContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getMovieActors": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"actors": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Actor))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/playlists/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => PlaylistResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/playlists/<playlist_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"playlist": autoguard.guards.Reference.of(() => Playlist)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getPlaylistItems": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"items": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => PlaylistItem))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getPlaylistContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => PlaylistContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/seasons/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => SeasonResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/seasons/<season_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"season": autoguard.guards.Reference.of(() => Season)
			}, {
				"last": autoguard.guards.Reference.of(() => Season),
				"next": autoguard.guards.Reference.of(() => Season)
			})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getSeasonEpisodes": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"episodes": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Episode))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getSeasonContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => SeasonContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/shows/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => ShowResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/shows/<show_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"show": autoguard.guards.Reference.of(() => Show),
				"actors": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Actor))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getShowSeasons": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"seasons": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Season))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getShowContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => ShowContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getShowActors": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"actors": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Actor))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/tracks/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => TrackResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/tracks/<track_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"track": autoguard.guards.Reference.of(() => Track)
			}, {
				"last": autoguard.guards.Reference.of(() => Track),
				"next": autoguard.guards.Reference.of(() => Track)
			})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/tracks/<track_id>/playlists/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"playlists": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Playlist))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getTrackContext": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"context": autoguard.guards.Reference.of(() => TrackContext)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/users/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => UserResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/users/<user_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"user": autoguard.guards.Reference.of(() => User)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/users/<user_id>/albums/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"albums": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Album))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"getUserArtists": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"artists": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Artist))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/users/<user_id>/playlists/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"playlists": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Playlist))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/users/<user_id>/shows/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"shows": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Show))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/years/<query>": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"results": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => YearResult))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/years/<year_id>/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"year": autoguard.guards.Reference.of(() => Year)
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/years/<year_id>/albums/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"albums": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Album))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/years/<year_id>/movies/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"movies": autoguard.guards.Array.of(autoguard.guards.Reference.of(() => Movie))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		}),
		"GET:/files/<file_id>/": autoguard.guards.Object.of({}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			),
			"payload": autoguard.api.Binary
		}),
		"GET:/statistics/": autoguard.guards.Object.of({
			"payload": autoguard.guards.Object.of({
				"statistics": autoguard.guards.Array.of(autoguard.guards.Object.of({
					"title": autoguard.guards.String,
					"value": autoguard.guards.Number
				}, {
					"unit": autoguard.guards.Union.of(
						autoguard.guards.StringLiteral.of("BYTES"),
						autoguard.guards.StringLiteral.of("MILLISECONDS")
					)
				}))
			}, {})
		}, {
			"status": autoguard.guards.Number,
			"headers": autoguard.guards.Intersection.of(
				autoguard.guards.Object.of({}, {}),
				autoguard.api.Headers
			)
		})
	};

	export type Responses = { [A in keyof typeof Responses]: ReturnType<typeof Responses[A]["as"]>; };
};
