// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { Playlist } from "../../database/schema";
import { PlaylistItem } from "../../database/schema";
import { guards as autoguard } from "@joelek/ts-autoguard";

export type SetToken = {
	"token"?: string
};

export const SetToken = autoguard.Object.of<SetToken>({
	"token": autoguard.Union.of(
		autoguard.Undefined,
		autoguard.String
	)
});

export type ErrorMessage = {
	"errors": string[]
};

export const ErrorMessage = autoguard.Object.of<ErrorMessage>({
	"errors": autoguard.Array.of(autoguard.String)
});

export type CreatePlaylistRequest = {
	"title": string,
	"description": string
};

export const CreatePlaylistRequest = autoguard.Object.of<CreatePlaylistRequest>({
	"title": autoguard.String,
	"description": autoguard.String
});

export type CreatePlaylistResponse = {
	"playlist": Playlist
};

export const CreatePlaylistResponse = autoguard.Object.of<CreatePlaylistResponse>({
	"playlist": autoguard.Reference.of<Playlist>(() => Playlist)
});

export type DeletePlaylistRequest = {
	"playlist_id": string
};

export const DeletePlaylistRequest = autoguard.Object.of<DeletePlaylistRequest>({
	"playlist_id": autoguard.String
});

export type DeletePlaylistResponse = {
	"playlist_id": string
};

export const DeletePlaylistResponse = autoguard.Object.of<DeletePlaylistResponse>({
	"playlist_id": autoguard.String
});

export type UpdatePlaylistRequest = {
	"playlist_id": string,
	"title": string,
	"description": string
};

export const UpdatePlaylistRequest = autoguard.Object.of<UpdatePlaylistRequest>({
	"playlist_id": autoguard.String,
	"title": autoguard.String,
	"description": autoguard.String
});

export type UpdatePlaylistResponse = {
	"playlist": Playlist
};

export const UpdatePlaylistResponse = autoguard.Object.of<UpdatePlaylistResponse>({
	"playlist": autoguard.Reference.of<Playlist>(() => Playlist)
});

export type CreatePlaylistItemRequest = {
	"playlist_id": string,
	"track_id": string
};

export const CreatePlaylistItemRequest = autoguard.Object.of<CreatePlaylistItemRequest>({
	"playlist_id": autoguard.String,
	"track_id": autoguard.String
});

export type CreatePlaylistItemResponse = {
	"playlist_item": PlaylistItem
};

export const CreatePlaylistItemResponse = autoguard.Object.of<CreatePlaylistItemResponse>({
	"playlist_item": autoguard.Reference.of<PlaylistItem>(() => PlaylistItem)
});

export type DeletePlaylistItemRequest = {
	"playlist_item_id": string
};

export const DeletePlaylistItemRequest = autoguard.Object.of<DeletePlaylistItemRequest>({
	"playlist_item_id": autoguard.String
});

export type DeletePlaylistItemResponse = {
	"playlist_item_id": string
};

export const DeletePlaylistItemResponse = autoguard.Object.of<DeletePlaylistItemResponse>({
	"playlist_item_id": autoguard.String
});

export type UpdatePlaylistItemRequest = {
	"playlist_item_id": string,
	"number": number
};

export const UpdatePlaylistItemRequest = autoguard.Object.of<UpdatePlaylistItemRequest>({
	"playlist_item_id": autoguard.String,
	"number": autoguard.Number
});

export type UpdatePlaylistItemResponse = {
	"playlist_item": PlaylistItem
};

export const UpdatePlaylistItemResponse = autoguard.Object.of<UpdatePlaylistItemResponse>({
	"playlist_item": autoguard.Reference.of<PlaylistItem>(() => PlaylistItem)
});

export type Autoguard = {
	"SetToken": SetToken,
	"ErrorMessage": ErrorMessage,
	"CreatePlaylistRequest": CreatePlaylistRequest,
	"CreatePlaylistResponse": CreatePlaylistResponse,
	"DeletePlaylistRequest": DeletePlaylistRequest,
	"DeletePlaylistResponse": DeletePlaylistResponse,
	"UpdatePlaylistRequest": UpdatePlaylistRequest,
	"UpdatePlaylistResponse": UpdatePlaylistResponse,
	"CreatePlaylistItemRequest": CreatePlaylistItemRequest,
	"CreatePlaylistItemResponse": CreatePlaylistItemResponse,
	"DeletePlaylistItemRequest": DeletePlaylistItemRequest,
	"DeletePlaylistItemResponse": DeletePlaylistItemResponse,
	"UpdatePlaylistItemRequest": UpdatePlaylistItemRequest,
	"UpdatePlaylistItemResponse": UpdatePlaylistItemResponse
};

export const Autoguard = {
	"SetToken": SetToken,
	"ErrorMessage": ErrorMessage,
	"CreatePlaylistRequest": CreatePlaylistRequest,
	"CreatePlaylistResponse": CreatePlaylistResponse,
	"DeletePlaylistRequest": DeletePlaylistRequest,
	"DeletePlaylistResponse": DeletePlaylistResponse,
	"UpdatePlaylistRequest": UpdatePlaylistRequest,
	"UpdatePlaylistResponse": UpdatePlaylistResponse,
	"CreatePlaylistItemRequest": CreatePlaylistItemRequest,
	"CreatePlaylistItemResponse": CreatePlaylistItemResponse,
	"DeletePlaylistItemRequest": DeletePlaylistItemRequest,
	"DeletePlaylistItemResponse": DeletePlaylistItemResponse,
	"UpdatePlaylistItemRequest": UpdatePlaylistItemRequest,
	"UpdatePlaylistItemResponse": UpdatePlaylistItemResponse
};
