// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type VideoFrame = {
	"pkt_pts_time": string
};

export const VideoFrame = autoguard.Object.of({
	"pkt_pts_time": autoguard.String
});

export type ShowFrames = {
	"frames": VideoFrame[]
};

export const ShowFrames = autoguard.Object.of({
	"frames": autoguard.Array.of(VideoFrame)
});

export type Stream = {
	"start_time": string,
	"duration": string
};

export const Stream = autoguard.Object.of({
	"start_time": autoguard.String,
	"duration": autoguard.String
});

export type ShowStreams = {
	"streams": Stream[]
};

export const ShowStreams = autoguard.Object.of({
	"streams": autoguard.Array.of(Stream)
});

export type Autoguard = {
	"VideoFrame": VideoFrame,
	"ShowFrames": ShowFrames,
	"Stream": Stream,
	"ShowStreams": ShowStreams
};

export const Autoguard = {
	"VideoFrame": VideoFrame,
	"ShowFrames": ShowFrames,
	"Stream": Stream,
	"ShowStreams": ShowStreams
};
