// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard";

export type VideoFrame = {
	"pkt_pts_time": string
};

export const VideoFrame = {
	as(subject: any, path: string = ""): VideoFrame {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				(autoguard.guards.String.as)(subject["pkt_pts_time"], path + "[\"pkt_pts_time\"]");
				return subject;
			}
			throw "Type guard \"Object\" failed at \"" + path + "\"!";
		})(subject, path);
	},
	is(subject: any): subject is VideoFrame {
		try {
			VideoFrame.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type ShowFrames = {
	"frames": VideoFrame[]
};

export const ShowFrames = {
	as(subject: any, path: string = ""): ShowFrames {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(VideoFrame.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Type guard \"Array\" failed at \"" + path + "\"!";
				})(subject["frames"], path + "[\"frames\"]");
				return subject;
			}
			throw "Type guard \"Object\" failed at \"" + path + "\"!";
		})(subject, path);
	},
	is(subject: any): subject is ShowFrames {
		try {
			ShowFrames.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type Autoguard = {
	"VideoFrame": VideoFrame,
	"ShowFrames": ShowFrames
};

export const Autoguard = {
	"VideoFrame": VideoFrame,
	"ShowFrames": ShowFrames
};
