// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

export type DeviceAvailable = {};

export const DeviceAvailable = {
	as(subject: any, path: string = ""): DeviceAvailable {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				return subject;
			}
			throw "Expected an object at " + path + "!";
		})(subject, path);
	},
	is(subject: any): subject is DeviceAvailable {
		try {
			this.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type Autoguard = {
	"DeviceAvailable": DeviceAvailable
};

export const Autoguard = {
	"DeviceAvailable": DeviceAvailable
};
