// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type DeviceBecameAvailable = {
	"id": string
};

export const DeviceBecameAvailable = autoguard.Object.of<DeviceBecameAvailable>({
	"id": autoguard.String
});

export type DeviceBecameUnavailable = {
	"id": string
};

export const DeviceBecameUnavailable = autoguard.Object.of<DeviceBecameUnavailable>({
	"id": autoguard.String
});

export type GetDevicesAvailable = {};

export const GetDevicesAvailable = autoguard.Object.of<GetDevicesAvailable>({});

export type Autoguard = {
	"DeviceBecameAvailable": DeviceBecameAvailable,
	"DeviceBecameUnavailable": DeviceBecameUnavailable,
	"GetDevicesAvailable": GetDevicesAvailable
};

export const Autoguard = {
	"DeviceBecameAvailable": DeviceBecameAvailable,
	"DeviceBecameUnavailable": DeviceBecameUnavailable,
	"GetDevicesAvailable": GetDevicesAvailable
};
