// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard";

export type EpisodeMetadata = {
	"type": "episode",
	"imdb": string,
	"title": string,
	"year": number,
	"summary": string,
	"show": {
		"imdb": string,
		"title": string,
		"genres": string[]
	},
	"season": number,
	"episode": number
};

export const EpisodeMetadata = {
	as(subject: any, path: string = ""): EpisodeMetadata {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if (subject === "episode") {
						return subject;
					}
					throw "Type guard \"StringLiteral\" failed at \"" + path + "\"!";
				})(subject["type"], path + "[\"type\"]");
				(autoguard.guards.String.as)(subject["imdb"], path + "[\"imdb\"]");
				(autoguard.guards.String.as)(subject["title"], path + "[\"title\"]");
				(autoguard.guards.Number.as)(subject["year"], path + "[\"year\"]");
				(autoguard.guards.String.as)(subject["summary"], path + "[\"summary\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Object)) {
						(autoguard.guards.String.as)(subject["imdb"], path + "[\"imdb\"]");
						(autoguard.guards.String.as)(subject["title"], path + "[\"title\"]");
						((subject, path) => {
							if ((subject != null) && (subject.constructor === globalThis.Array)) {
								for (let i = 0; i < subject.length; i++) {
									(autoguard.guards.String.as)(subject[i], path + "[" + i + "]");
								}
								return subject;
							}
							throw "Type guard \"Array\" failed at \"" + path + "\"!";
						})(subject["genres"], path + "[\"genres\"]");
						return subject;
					}
					throw "Type guard \"Object\" failed at \"" + path + "\"!";
				})(subject["show"], path + "[\"show\"]");
				(autoguard.guards.Number.as)(subject["season"], path + "[\"season\"]");
				(autoguard.guards.Number.as)(subject["episode"], path + "[\"episode\"]");
				return subject;
			}
			throw "Type guard \"Object\" failed at \"" + path + "\"!";
		})(subject, path);
	},
	is(subject: any): subject is EpisodeMetadata {
		try {
			EpisodeMetadata.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type MovieMetadata = {
	"type": "movie",
	"imdb": string,
	"title": string,
	"year": number,
	"summary": string,
	"genres": string[]
};

export const MovieMetadata = {
	as(subject: any, path: string = ""): MovieMetadata {
		return ((subject, path) => {
			if ((subject != null) && (subject.constructor === globalThis.Object)) {
				((subject, path) => {
					if (subject === "movie") {
						return subject;
					}
					throw "Type guard \"StringLiteral\" failed at \"" + path + "\"!";
				})(subject["type"], path + "[\"type\"]");
				(autoguard.guards.String.as)(subject["imdb"], path + "[\"imdb\"]");
				(autoguard.guards.String.as)(subject["title"], path + "[\"title\"]");
				(autoguard.guards.Number.as)(subject["year"], path + "[\"year\"]");
				(autoguard.guards.String.as)(subject["summary"], path + "[\"summary\"]");
				((subject, path) => {
					if ((subject != null) && (subject.constructor === globalThis.Array)) {
						for (let i = 0; i < subject.length; i++) {
							(autoguard.guards.String.as)(subject[i], path + "[" + i + "]");
						}
						return subject;
					}
					throw "Type guard \"Array\" failed at \"" + path + "\"!";
				})(subject["genres"], path + "[\"genres\"]");
				return subject;
			}
			throw "Type guard \"Object\" failed at \"" + path + "\"!";
		})(subject, path);
	},
	is(subject: any): subject is MovieMetadata {
		try {
			MovieMetadata.as(subject);
		} catch (error) {
			return false;
		}
		return true;
	}
};

export type Autoguard = {
	"EpisodeMetadata": EpisodeMetadata,
	"MovieMetadata": MovieMetadata
};

export const Autoguard = {
	"EpisodeMetadata": EpisodeMetadata,
	"MovieMetadata": MovieMetadata
};
